### PR TITLE
feat: add output format option with 'gcc'

### PR DESCRIPTION
**Pull request by vnayar**
Relating to #145, a new command-line option  was added. The current output format is named 'default', and a new format 'gcc' was added that uses an error format similar
to gcc, namely:  `<file>:<lineNo>:<charNo>: <type/severity>: <message>`

This command-line option mirrors that used by the common linting tool shellcheck: https://www.mankier.com/1/shellcheck

Example output:
```
$ ./bin/ec --format=gcc ~/files/dummy.*
../../files/dummy.bat:0:0: error: Wrong line endings or no final newline
../../files/dummy.bat:0:0: error: Not all lines have the correct end of line character
../../files/dummy.d:2:0: error: Line too long (113 instead of 100)
../../files/dummy.d:3:0: error: Wrong amount of left-padding spaces(want multiple of 2)
```

### CODE REVIEW

**Comment by vnayar** [comment]
I modified the commit description to have the prefix `feat:`, which I believe is what was causing the build to fail, although I'm not 100% sure.  Please approve execution of the workflow.

**Comment by vnayar** [comment]
Another force-push due to the subject line of the commit being rejected with the following error:
```
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
```
I am guessing that capitalizing the letters in the subject will resolve this, but I have no way of checking until the workflow is run.

**Comment by vnayar** [comment]
I cannot find any documentation regarding the proper case for commit message titles, but all the other examples that are present use lower case. I am making yet another attempt to satisfy this commit linting tool. Please re-run the workflow, because currently only maintainers can do this.

**Comment by vnayar** [comment]
Updated `testfiles/generated-config` to include an empty "format" value.

**Comment by vnayar** [comment]
When time permits, please take a look. The option to alter the output format is called "--format" and the first added alternative is "gcc". The output format and commnd-line options are inspired from https://www.shellcheck.net/

**Comment by vnayar** [comment]
@mstruebing Could you take a moment to look at this PR to add a `--format` option, with one additional format so far, `--format=gcc`, which outputs line-oriented output similar to `gcc`. The option name and value were borrowed from the common linting tool `shellcheck`.

**Review by mstruebing — APPROVED** [review]
Thank you this is a good PR.
Sorry for taking so long.

**Comment by mstruebing** [comment]
I've created a new release, 2.8.
Can #145 be closed or does this issue still needs to be open or can it be closed?

**Comment by vnayar** [comment]
> I've created a new release, 2.8. Can #145 be closed or does this issue still needs to be open or can it be closed?

I believe all the described conditions of #145 have been satisfied, namely:
> Though the output of editorconfig-checker is human friendly, it is complicated to parse in other tools. A more repetitive one line output format is basic but at least somewhat common. An option to fully print each error per line would be great.

**Pull request merged**
