### PR TITLE
chore(release): v3.0.2

### PR DESCRIPTION
**Pull request by theoludwig**
## What's Changed
* fix: indent_style = space is ignored if indent_size = unset (#277) by @haumont in https://github.com/editorconfig-checker/editorconfig-checker/pull/331
* fix: v3 prefix is required by @greut in https://github.com/editorconfig-checker/editorconfig-checker/pull/339
* fix: io/ioutil is deprecated by @greut in https://github.com/editorconfig-checker/editorconfig-checker/pull/340
* fix: check if multiple newlines are at EOF by @holesch in https://github.com/editorconfig-checker/editorconfig-checker/pull/350

## New Contributors
* @haumont made their first contribution in https://github.com/editorconfig-checker/editorconfig-checker/pull/331
* @holesch made their first contribution in https://github.com/editorconfig-checker/editorconfig-checker/pull/350

**Full Changelog**: https://github.com/editorconfig-checker/editorconfig-checker/compare/v3.0.1...v3.0.2

### CODE REVIEW

**Comment by theoludwig** [comment]
@mstruebing Time to do a new release? :smile:

What are the things to do, to do a new release?

**Comment by mstruebing** [comment]
Right now it's a mess,  that's what #150 is for

You need to check out the `main` branch and execute `make release`: https://github.com/editorconfig-checker/editorconfig-checker/blob/main/Makefile#L58-L159

This does a couple of steps:

1. It checks if you are on `main` and if it's up to date to make sure nothing got merged in between your last local state
2. It creates a new release branch locally and deletes your files in `bin` to make sure there are no leftovers
3. It prints the current version and asks you to input the new version you want to release, there is no further check though that this version makes sense except that it's prefixed with `v`
4. Then it does some `sed` magic to update all necessary files and commits that into the release branch and creates a git tag
5. It builds and compresses all binaries so you have a bunch of `tar.gz` files in `bin` then for every platform I was able to make it work when I've build that
6. Then it checks out `main` and merges the release branch into it and pushes that as well as the tags


You then need to manually create a GitHub release and upload the binaries and the release is done 🎉 

I could do it if you feel overwhelmed by this right now :D

**Comment by theoludwig** [comment]
> I could do it if you feel overwhelmed by this right now :D

Yes, do it, please. :heart:

Thank you!

(feel free to close this PR and delete the `release` branch, and the v3.02 tag I created manually).

**Comment by mstruebing** [comment]
@theoludwig here it is: https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/v3.0.2
Sorry for not creating a more straightforward release process. It would be amazing to have.

**Pull request closed without merging**
