### PR TITLE
mod: bump core to 2.1.1

### PR DESCRIPTION
**Pull request by greut**
The check should probably be made into editorconfig-core-go instead. Let me know what you think.

### CODE REVIEW

**Comment by mstruebing** [comment]
Hey thanks for your PR!
Are you sure this is needed - because travis ran through even without the `abs` thingy. Just asking :)

**Comment by greut** [comment]
@mstruebing it is, but I'll perform the fix in the core lib.

**Comment by greut** [comment]
Waiting for 2.1.1

```console
[33;1mcmd/editorconfig-checker/main_test.go:[33;0m
[31;1m	4: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	5: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	6: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	10: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	11: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	12: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	13: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	14: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	15: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	16: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	18: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	19: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	20: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m	21: Wrong amount of left-padding spaces(want multiple of 4)[33;0m
[31;1m
14 errors found[33;0m
```

**Comment by mstruebing** [comment]
Great, thank you! :)

**Comment by greut** [comment]
```
$ bin/ec -v
Exclude Regexp: testfiles|yarn\.lock$|package-lock\.json|composer\.lock$|\.snap$|\.otf$|\.woff$|\.woff2$|\.eot$|\.ttf$|\.gif$|\.png$|\.jpg$|\.jpeg$|\.mp4$|\.wmv$|\.svg$|\.ico$|\.bak$|\.bin$|\.pdf$|\.zip$|\.gz$|\.tar$|\.7z$|\.bz2$|\.log$|\.css\.map$|\.js\.map$|min\.css$|min\.js$
Add .ecrc to be checked
Add .editorconfig to be checked
Add .gitignore to be checked
Add .travis.yml to be checked
Add CHANGELOG.md to be checked
Add Dockerfile to be checked
Add LICENSE to be checked
Add Makefile to be checked
Add README.md to be checked
Add cmd/editorconfig-checker/main.go to be checked
Add cmd/editorconfig-checker/main_test.go to be checked
Don't add docs/logo.png to be checked
Don't add docs/screenshot.png to be checked
Add go.mod to be checked
Add go.sum to be checked
Add pkg/config/config.go to be checked
Add pkg/config/config_test.go to be checked
Add pkg/error/error.go to be checked
Add pkg/error/error_test.go to be checked
Add pkg/files/files.go to be checked
Add pkg/files/files_test.go to be checked
Add pkg/logger/logger.go to be checked
Add pkg/logger/logger_test.go to be checked
Add pkg/utils/utils.go to be checked
Add pkg/utils/utils_test.go to be checked
Add pkg/validation/validation.go to be checked
Add pkg/validation/validation_test.go to be checked
Add pkg/validation/validators/validators.go to be checked
Add pkg/validation/validators/validators_test.go to be checked
Don't add testfiles/.ecrc to be checked
Don't add testfiles/.editorconfig to be checked
Don't add testfiles/.malformed.ecrc to be checked
Don't add testfiles/disabled-file.ext to be checked
Don't add testfiles/disabled-line.txt to be checked
Don't add testfiles/empty-file.txt to be checked
Don't add testfiles/final-newline-missing.txt to be checked
Don't add testfiles/generated-config.json to be checked
Don't add testfiles/spaces-after-tabs.txt to be checked
Don't add testfiles/trailing-whitespace.txt to be checked
Don't add testfiles/wrong-file.txt to be checked
Don't add testfiles/wrong-line-ending.txt to be checked
Don't add testfiles/zero-indent.txt to be checked
Validate .ecrc
Validate .editorconfig
Validate .gitignore
Validate .travis.yml
Validate CHANGELOG.md
Validate Dockerfile
Validate LICENSE
Validate Makefile
Validate README.md
Validate cmd/editorconfig-checker/main.go
Validate cmd/editorconfig-checker/main_test.go
Validate go.mod
Validate go.sum
Validate pkg/config/config.go
Validate pkg/config/config_test.go
Validate pkg/error/error.go
Validate pkg/error/error_test.go
Validate pkg/files/files.go
Validate pkg/files/files_test.go
Validate pkg/logger/logger.go
Validate pkg/logger/logger_test.go
Validate pkg/utils/utils.go
Validate pkg/utils/utils_test.go
Validate pkg/validation/validation.go
Validate pkg/validation/validation_test.go
Validate pkg/validation/validators/validators.go
Validate pkg/validation/validators/validators_test.go
27 files checked
```

**Pull request merged**
